### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by syguan96** [snap-research/Panda-70M#46]
The expected name is `653c8d37-f750-4ef4-90b8-e39de0606e72.mp4`. But the actual name is `653c8d37-f750-4ef4-90b8-e39de0606e72.f230.mp4`. Has anyone met this error?

**Comment by tsaishien-chen** [comment]
Hi @syguan96,

Thanks for your interest in Panda-70M dataset.
This is expected. As yt-dlp will download the video in part and combine them together after all downloading is finished.
For example:
![image](https://github.com/snap-research/Panda-70M/assets/43384650/76fb4fc3-7eb3-482e-b4e8-62bedc3eccf2)
In this case, the whole video into two files `...[gsnqXt7d1mU].f614.mp4` and `...[gsnqXt7d1mU].f234.mp4`.
After both of them are prepared, they will be merged and deleted.

Does this cause your problem? If yes, I believe that is because the downloading is interrupted.

**Comment by syguan96** [comment]
Thank you!
